--------------------------------------------------------------------
-- Source: Linux Acadamey PostgreSQL Administration Deep Dive Course
-- Author: Landon Fowler
-- Purpose: SQL script for loading the sales.state table of 'acweb'
-- Date Updated: 03/05/2020
--------------------------------------------------------------------

insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Virginia');
insert into sales.state (name) values ('Missouri');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Kansas');
insert into sales.state (name) values ('Massachusetts');
insert into sales.state (name) values ('Tennessee');
insert into sales.state (name) values ('Tennessee');
insert into sales.state (name) values ('Michigan');
insert into sales.state (name) values ('Virginia');
insert into sales.state (name) values ('Kansas');
insert into sales.state (name) values ('North Carolina');
insert into sales.state (name) values ('Alabama');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Georgia');
insert into sales.state (name) values ('Minnesota');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Michigan');
insert into sales.state (name) values ('Illinois');
insert into sales.state (name) values ('Louisiana');
insert into sales.state (name) values ('Tennessee');
insert into sales.state (name) values ('Oklahoma');
insert into sales.state (name) values ('Ohio');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Virginia');
insert into sales.state (name) values ('West Virginia');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Virginia');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('New Jersey');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Connecticut');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('North Carolina');
insert into sales.state (name) values ('Virginia');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Louisiana');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Washington');
insert into sales.state (name) values ('North Carolina');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Ohio');
insert into sales.state (name) values ('Washington');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Arkansas');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('West Virginia');
insert into sales.state (name) values ('Washington');
insert into sales.state (name) values ('Utah');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Louisiana');
insert into sales.state (name) values ('Arkansas');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Ohio');
insert into sales.state (name) values ('Alabama');
insert into sales.state (name) values ('Illinois');
insert into sales.state (name) values ('New Jersey');
insert into sales.state (name) values ('Pennsylvania');
insert into sales.state (name) values ('Louisiana');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Massachusetts');
insert into sales.state (name) values ('Indiana');
insert into sales.state (name) values ('Colorado');
insert into sales.state (name) values ('Colorado');
insert into sales.state (name) values ('Kansas');
insert into sales.state (name) values ('Illinois');
insert into sales.state (name) values ('Utah');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Indiana');
insert into sales.state (name) values ('Virginia');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('North Carolina');
insert into sales.state (name) values ('New Mexico');
insert into sales.state (name) values ('Georgia');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Michigan');
insert into sales.state (name) values ('Oregon');
insert into sales.state (name) values ('Washington');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Kansas');
insert into sales.state (name) values ('Arizona');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Pennsylvania');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Georgia');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Ohio');
insert into sales.state (name) values ('Maryland');
insert into sales.state (name) values ('Ohio');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Alabama');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Massachusetts');
insert into sales.state (name) values ('Nevada');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Missouri');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('District of Columbia');
insert into sales.state (name) values ('Pennsylvania');
insert into sales.state (name) values ('Virginia');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Minnesota');
insert into sales.state (name) values ('Illinois');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Ohio');
insert into sales.state (name) values ('Ohio');
insert into sales.state (name) values ('Alabama');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Massachusetts');
insert into sales.state (name) values ('Georgia');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Oklahoma');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Washington');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Kentucky');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('South Dakota');
insert into sales.state (name) values ('Nevada');
insert into sales.state (name) values ('District of Columbia');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Alabama');
insert into sales.state (name) values ('Tennessee');
insert into sales.state (name) values ('Illinois');
insert into sales.state (name) values ('Ohio');
insert into sales.state (name) values ('Georgia');
insert into sales.state (name) values ('Tennessee');
insert into sales.state (name) values ('Colorado');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Colorado');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Utah');
insert into sales.state (name) values ('District of Columbia');
insert into sales.state (name) values ('Alabama');
insert into sales.state (name) values ('Alabama');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Maryland');
insert into sales.state (name) values ('Michigan');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Delaware');
insert into sales.state (name) values ('Louisiana');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Utah');
insert into sales.state (name) values ('Delaware');
insert into sales.state (name) values ('Missouri');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Nebraska');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Ohio');
insert into sales.state (name) values ('New Jersey');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Ohio');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('New Mexico');
insert into sales.state (name) values ('Ohio');
insert into sales.state (name) values ('Oklahoma');
insert into sales.state (name) values ('South Carolina');
insert into sales.state (name) values ('Louisiana');
insert into sales.state (name) values ('Alaska');
insert into sales.state (name) values ('Ohio');
insert into sales.state (name) values ('Washington');
insert into sales.state (name) values ('Arizona');
insert into sales.state (name) values ('Minnesota');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('District of Columbia');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Minnesota');
insert into sales.state (name) values ('Tennessee');
insert into sales.state (name) values ('Tennessee');
insert into sales.state (name) values ('Arizona');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Illinois');
insert into sales.state (name) values ('Colorado');
insert into sales.state (name) values ('Kansas');
insert into sales.state (name) values ('Tennessee');
insert into sales.state (name) values ('Georgia');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Illinois');
insert into sales.state (name) values ('Virginia');
insert into sales.state (name) values ('Wisconsin');
insert into sales.state (name) values ('North Carolina');
insert into sales.state (name) values ('Georgia');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('North Carolina');
insert into sales.state (name) values ('Tennessee');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Ohio');
insert into sales.state (name) values ('Arizona');
insert into sales.state (name) values ('Connecticut');
insert into sales.state (name) values ('Colorado');
insert into sales.state (name) values ('Maryland');
insert into sales.state (name) values ('Missouri');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('District of Columbia');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Oklahoma');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('New Jersey');
insert into sales.state (name) values ('Ohio');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Missouri');
insert into sales.state (name) values ('Connecticut');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Kentucky');
insert into sales.state (name) values ('Tennessee');
insert into sales.state (name) values ('District of Columbia');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Indiana');
insert into sales.state (name) values ('North Carolina');
insert into sales.state (name) values ('Missouri');
insert into sales.state (name) values ('Colorado');
insert into sales.state (name) values ('Arizona');
insert into sales.state (name) values ('District of Columbia');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('District of Columbia');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Arizona');
insert into sales.state (name) values ('District of Columbia');
insert into sales.state (name) values ('Colorado');
insert into sales.state (name) values ('Kentucky');
insert into sales.state (name) values ('Iowa');
insert into sales.state (name) values ('West Virginia');
insert into sales.state (name) values ('Tennessee');
insert into sales.state (name) values ('Kentucky');
insert into sales.state (name) values ('Kansas');
insert into sales.state (name) values ('Illinois');
insert into sales.state (name) values ('Washington');
insert into sales.state (name) values ('Arkansas');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('South Carolina');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('District of Columbia');
insert into sales.state (name) values ('New Jersey');
insert into sales.state (name) values ('Michigan');
insert into sales.state (name) values ('Indiana');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Connecticut');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Virginia');
insert into sales.state (name) values ('Pennsylvania');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Ohio');
insert into sales.state (name) values ('Kansas');
insert into sales.state (name) values ('Illinois');
insert into sales.state (name) values ('Tennessee');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Connecticut');
insert into sales.state (name) values ('Missouri');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Arizona');
insert into sales.state (name) values ('Illinois');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Louisiana');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Illinois');
insert into sales.state (name) values ('Indiana');
insert into sales.state (name) values ('Minnesota');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Ohio');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Michigan');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Louisiana');
insert into sales.state (name) values ('Ohio');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Arizona');
insert into sales.state (name) values ('Louisiana');
insert into sales.state (name) values ('Kentucky');
insert into sales.state (name) values ('North Carolina');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Ohio');
insert into sales.state (name) values ('Washington');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('New Jersey');
insert into sales.state (name) values ('Alabama');
insert into sales.state (name) values ('Illinois');
insert into sales.state (name) values ('Missouri');
insert into sales.state (name) values ('Massachusetts');
insert into sales.state (name) values ('Pennsylvania');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Oregon');
insert into sales.state (name) values ('Missouri');
insert into sales.state (name) values ('South Dakota');
insert into sales.state (name) values ('Virginia');
insert into sales.state (name) values ('Ohio');
insert into sales.state (name) values ('Louisiana');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Idaho');
insert into sales.state (name) values ('Georgia');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Kansas');
insert into sales.state (name) values ('South Carolina');
insert into sales.state (name) values ('Mississippi');
insert into sales.state (name) values ('Oregon');
insert into sales.state (name) values ('North Carolina');
insert into sales.state (name) values ('Colorado');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Minnesota');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Missouri');
insert into sales.state (name) values ('Virginia');
insert into sales.state (name) values ('Washington');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Illinois');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Nevada');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Colorado');
insert into sales.state (name) values ('Wisconsin');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Arkansas');
insert into sales.state (name) values ('Nebraska');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Virginia');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Pennsylvania');
insert into sales.state (name) values ('Ohio');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Colorado');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Mississippi');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Illinois');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Indiana');
insert into sales.state (name) values ('West Virginia');
insert into sales.state (name) values ('Virginia');
insert into sales.state (name) values ('Georgia');
insert into sales.state (name) values ('Nevada');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Colorado');
insert into sales.state (name) values ('North Carolina');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Georgia');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('District of Columbia');
insert into sales.state (name) values ('Minnesota');
insert into sales.state (name) values ('Indiana');
insert into sales.state (name) values ('Nebraska');
insert into sales.state (name) values ('Georgia');
insert into sales.state (name) values ('Virginia');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Massachusetts');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Idaho');
insert into sales.state (name) values ('Maryland');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('South Carolina');
insert into sales.state (name) values ('Virginia');
insert into sales.state (name) values ('Alaska');
insert into sales.state (name) values ('Ohio');
insert into sales.state (name) values ('Connecticut');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Arizona');
insert into sales.state (name) values ('Georgia');
insert into sales.state (name) values ('District of Columbia');
insert into sales.state (name) values ('Illinois');
insert into sales.state (name) values ('Colorado');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Washington');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Kentucky');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Ohio');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Washington');
insert into sales.state (name) values ('South Dakota');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Missouri');
insert into sales.state (name) values ('Virginia');
insert into sales.state (name) values ('Michigan');
insert into sales.state (name) values ('Virginia');
insert into sales.state (name) values ('Colorado');
insert into sales.state (name) values ('Pennsylvania');
insert into sales.state (name) values ('Colorado');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Alabama');
insert into sales.state (name) values ('Wisconsin');
insert into sales.state (name) values ('Arkansas');
insert into sales.state (name) values ('Michigan');
insert into sales.state (name) values ('New Jersey');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('New Jersey');
insert into sales.state (name) values ('Colorado');
insert into sales.state (name) values ('Pennsylvania');
insert into sales.state (name) values ('New Jersey');
insert into sales.state (name) values ('Louisiana');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('District of Columbia');
insert into sales.state (name) values ('Massachusetts');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('New Jersey');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Tennessee');
insert into sales.state (name) values ('South Carolina');
insert into sales.state (name) values ('New Mexico');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Nevada');
insert into sales.state (name) values ('Alabama');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Georgia');
insert into sales.state (name) values ('Minnesota');
insert into sales.state (name) values ('Nevada');
insert into sales.state (name) values ('Louisiana');
insert into sales.state (name) values ('Connecticut');
insert into sales.state (name) values ('Virginia');
insert into sales.state (name) values ('Ohio');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Virginia');
insert into sales.state (name) values ('Illinois');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Alabama');
insert into sales.state (name) values ('Minnesota');
insert into sales.state (name) values ('Minnesota');
insert into sales.state (name) values ('Nebraska');
insert into sales.state (name) values ('Illinois');
insert into sales.state (name) values ('Iowa');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Colorado');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Massachusetts');
insert into sales.state (name) values ('Alabama');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Alabama');
insert into sales.state (name) values ('Illinois');
insert into sales.state (name) values ('Illinois');
insert into sales.state (name) values ('Georgia');
insert into sales.state (name) values ('Ohio');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Alabama');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Arizona');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Illinois');
insert into sales.state (name) values ('Minnesota');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Missouri');
insert into sales.state (name) values ('Iowa');
insert into sales.state (name) values ('Pennsylvania');
insert into sales.state (name) values ('Alabama');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Louisiana');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Wisconsin');
insert into sales.state (name) values ('Minnesota');
insert into sales.state (name) values ('Missouri');
insert into sales.state (name) values ('Maryland');
insert into sales.state (name) values ('Virginia');
insert into sales.state (name) values ('Nebraska');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Michigan');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('District of Columbia');
insert into sales.state (name) values ('Colorado');
insert into sales.state (name) values ('Georgia');
insert into sales.state (name) values ('Kansas');
insert into sales.state (name) values ('Virginia');
insert into sales.state (name) values ('Nebraska');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Wisconsin');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Virginia');
insert into sales.state (name) values ('Pennsylvania');
insert into sales.state (name) values ('Kansas');
insert into sales.state (name) values ('Washington');
insert into sales.state (name) values ('Idaho');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Arizona');
insert into sales.state (name) values ('Massachusetts');
insert into sales.state (name) values ('Georgia');
insert into sales.state (name) values ('Louisiana');
insert into sales.state (name) values ('Tennessee');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Massachusetts');
insert into sales.state (name) values ('Georgia');
insert into sales.state (name) values ('Oregon');
insert into sales.state (name) values ('Virginia');
insert into sales.state (name) values ('Arizona');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Kentucky');
insert into sales.state (name) values ('District of Columbia');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Arizona');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Mississippi');
insert into sales.state (name) values ('Massachusetts');
insert into sales.state (name) values ('Kentucky');
insert into sales.state (name) values ('New Jersey');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('North Carolina');
insert into sales.state (name) values ('Virginia');
insert into sales.state (name) values ('Missouri');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Kentucky');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Ohio');
insert into sales.state (name) values ('Alaska');
insert into sales.state (name) values ('Utah');
insert into sales.state (name) values ('Utah');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Nevada');
insert into sales.state (name) values ('Colorado');
insert into sales.state (name) values ('New Mexico');
insert into sales.state (name) values ('Wisconsin');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Arizona');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Massachusetts');
insert into sales.state (name) values ('Oklahoma');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('District of Columbia');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Arizona');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Minnesota');
insert into sales.state (name) values ('Colorado');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Indiana');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Colorado');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Colorado');
insert into sales.state (name) values ('Ohio');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Iowa');
insert into sales.state (name) values ('Ohio');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Connecticut');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Indiana');
insert into sales.state (name) values ('Kansas');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Arizona');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Missouri');
insert into sales.state (name) values ('District of Columbia');
insert into sales.state (name) values ('Delaware');
insert into sales.state (name) values ('District of Columbia');
insert into sales.state (name) values ('Pennsylvania');
insert into sales.state (name) values ('Wisconsin');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Maryland');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Ohio');
insert into sales.state (name) values ('Georgia');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Georgia');
insert into sales.state (name) values ('Colorado');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Virginia');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Virginia');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Pennsylvania');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Virginia');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Colorado');
insert into sales.state (name) values ('Tennessee');
insert into sales.state (name) values ('Arizona');
insert into sales.state (name) values ('Tennessee');
insert into sales.state (name) values ('Massachusetts');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Missouri');
insert into sales.state (name) values ('Pennsylvania');
insert into sales.state (name) values ('Georgia');
insert into sales.state (name) values ('Virginia');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Kentucky');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Colorado');
insert into sales.state (name) values ('District of Columbia');
insert into sales.state (name) values ('Nebraska');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Virginia');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Arizona');
insert into sales.state (name) values ('Tennessee');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Tennessee');
insert into sales.state (name) values ('Virginia');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Georgia');
insert into sales.state (name) values ('Alabama');
insert into sales.state (name) values ('Kentucky');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Ohio');
insert into sales.state (name) values ('Tennessee');
insert into sales.state (name) values ('West Virginia');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Colorado');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Minnesota');
insert into sales.state (name) values ('New Jersey');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Virginia');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Virginia');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Louisiana');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Louisiana');
insert into sales.state (name) values ('Louisiana');
insert into sales.state (name) values ('Pennsylvania');
insert into sales.state (name) values ('Oklahoma');
insert into sales.state (name) values ('Arizona');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Georgia');
insert into sales.state (name) values ('Idaho');
insert into sales.state (name) values ('Louisiana');
insert into sales.state (name) values ('Oklahoma');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Michigan');
insert into sales.state (name) values ('Kentucky');
insert into sales.state (name) values ('Iowa');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Virginia');
insert into sales.state (name) values ('Maryland');
insert into sales.state (name) values ('Missouri');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Ohio');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Oklahoma');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Washington');
insert into sales.state (name) values ('Ohio');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Illinois');
insert into sales.state (name) values ('Delaware');
insert into sales.state (name) values ('North Carolina');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('West Virginia');
insert into sales.state (name) values ('Ohio');
insert into sales.state (name) values ('Utah');
insert into sales.state (name) values ('Ohio');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Arizona');
insert into sales.state (name) values ('Arizona');
insert into sales.state (name) values ('Pennsylvania');
insert into sales.state (name) values ('Utah');
insert into sales.state (name) values ('Tennessee');
insert into sales.state (name) values ('Kansas');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Mississippi');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Kansas');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Colorado');
insert into sales.state (name) values ('Colorado');
insert into sales.state (name) values ('District of Columbia');
insert into sales.state (name) values ('Tennessee');
insert into sales.state (name) values ('Illinois');
insert into sales.state (name) values ('Michigan');
insert into sales.state (name) values ('Nebraska');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Washington');
insert into sales.state (name) values ('Indiana');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Alaska');
insert into sales.state (name) values ('Colorado');
insert into sales.state (name) values ('Oklahoma');
insert into sales.state (name) values ('Alabama');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Louisiana');
insert into sales.state (name) values ('Kansas');
insert into sales.state (name) values ('Colorado');
insert into sales.state (name) values ('Kentucky');
insert into sales.state (name) values ('Missouri');
insert into sales.state (name) values ('Pennsylvania');
insert into sales.state (name) values ('North Dakota');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Ohio');
insert into sales.state (name) values ('Louisiana');
insert into sales.state (name) values ('Ohio');
insert into sales.state (name) values ('Connecticut');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Virginia');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Missouri');
insert into sales.state (name) values ('Georgia');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Ohio');
insert into sales.state (name) values ('Nevada');
insert into sales.state (name) values ('Ohio');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Colorado');
insert into sales.state (name) values ('Ohio');
insert into sales.state (name) values ('Kansas');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('District of Columbia');
insert into sales.state (name) values ('Colorado');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Pennsylvania');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Iowa');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Arizona');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Tennessee');
insert into sales.state (name) values ('Georgia');
insert into sales.state (name) values ('Kansas');
insert into sales.state (name) values ('Kansas');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Louisiana');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Michigan');
insert into sales.state (name) values ('Wisconsin');
insert into sales.state (name) values ('Arizona');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Tennessee');
insert into sales.state (name) values ('Colorado');
insert into sales.state (name) values ('Ohio');
insert into sales.state (name) values ('Georgia');
insert into sales.state (name) values ('Georgia');
insert into sales.state (name) values ('Illinois');
insert into sales.state (name) values ('Ohio');
insert into sales.state (name) values ('Minnesota');
insert into sales.state (name) values ('Louisiana');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Virginia');
insert into sales.state (name) values ('Arizona');
insert into sales.state (name) values ('Arizona');
insert into sales.state (name) values ('Oklahoma');
insert into sales.state (name) values ('Colorado');
insert into sales.state (name) values ('Arizona');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Illinois');
insert into sales.state (name) values ('Alabama');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Kentucky');
insert into sales.state (name) values ('Kansas');
insert into sales.state (name) values ('Pennsylvania');
insert into sales.state (name) values ('Maryland');
insert into sales.state (name) values ('Massachusetts');
insert into sales.state (name) values ('District of Columbia');
insert into sales.state (name) values ('Colorado');
insert into sales.state (name) values ('Kentucky');
insert into sales.state (name) values ('Indiana');
insert into sales.state (name) values ('Minnesota');
insert into sales.state (name) values ('Ohio');
insert into sales.state (name) values ('North Carolina');
insert into sales.state (name) values ('Pennsylvania');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Alaska');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Wisconsin');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Iowa');
insert into sales.state (name) values ('Mississippi');
insert into sales.state (name) values ('Georgia');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Pennsylvania');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Georgia');
insert into sales.state (name) values ('Michigan');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Nevada');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Kentucky');
insert into sales.state (name) values ('Indiana');
insert into sales.state (name) values ('District of Columbia');
insert into sales.state (name) values ('North Carolina');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Arizona');
insert into sales.state (name) values ('Minnesota');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Illinois');
insert into sales.state (name) values ('Ohio');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Kansas');
insert into sales.state (name) values ('Oregon');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Connecticut');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('North Carolina');
insert into sales.state (name) values ('District of Columbia');
insert into sales.state (name) values ('Oklahoma');
insert into sales.state (name) values ('Alabama');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Kentucky');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Alabama');
insert into sales.state (name) values ('District of Columbia');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Pennsylvania');
insert into sales.state (name) values ('South Carolina');
insert into sales.state (name) values ('Massachusetts');
insert into sales.state (name) values ('District of Columbia');
insert into sales.state (name) values ('North Carolina');
insert into sales.state (name) values ('Virginia');
insert into sales.state (name) values ('District of Columbia');
insert into sales.state (name) values ('Georgia');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Tennessee');
insert into sales.state (name) values ('Missouri');
insert into sales.state (name) values ('Tennessee');
insert into sales.state (name) values ('Virginia');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Nevada');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Oregon');
insert into sales.state (name) values ('South Carolina');
insert into sales.state (name) values ('Louisiana');
insert into sales.state (name) values ('Missouri');
insert into sales.state (name) values ('Wisconsin');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('South Carolina');
insert into sales.state (name) values ('Tennessee');
insert into sales.state (name) values ('Rhode Island');
insert into sales.state (name) values ('Utah');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('North Carolina');
insert into sales.state (name) values ('Colorado');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Ohio');
insert into sales.state (name) values ('Georgia');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Nevada');
insert into sales.state (name) values ('Missouri');
insert into sales.state (name) values ('Virginia');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Georgia');
insert into sales.state (name) values ('North Carolina');
insert into sales.state (name) values ('Wisconsin');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Oklahoma');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Virginia');
insert into sales.state (name) values ('Virginia');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Washington');
insert into sales.state (name) values ('Georgia');
insert into sales.state (name) values ('Georgia');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Maryland');
insert into sales.state (name) values ('Michigan');
insert into sales.state (name) values ('Arizona');
insert into sales.state (name) values ('Missouri');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Virginia');
insert into sales.state (name) values ('Michigan');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Minnesota');
insert into sales.state (name) values ('Kansas');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Georgia');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('South Carolina');
insert into sales.state (name) values ('California');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('Ohio');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Georgia');
insert into sales.state (name) values ('Louisiana');
insert into sales.state (name) values ('Pennsylvania');
insert into sales.state (name) values ('Colorado');
insert into sales.state (name) values ('Indiana');
insert into sales.state (name) values ('Tennessee');
insert into sales.state (name) values ('Georgia');
insert into sales.state (name) values ('Virginia');
insert into sales.state (name) values ('Georgia');
insert into sales.state (name) values ('Colorado');
insert into sales.state (name) values ('Texas');
insert into sales.state (name) values ('New York');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Florida');
insert into sales.state (name) values ('Minnesota');
insert into sales.state (name) values ('Arizona');
insert into sales.state (name) values ('North Carolina');
insert into sales.state (name) values ('Maryland');
