--------------------------------------------------------------------
-- Source: Linux Acadamey PostgreSQL Administration Deep Dive Course
-- Author: Landon Fowler
-- Purpose: SQL script for loading the sales.city table of 'acweb'
-- Date Updated: 03/05/2020
--------------------------------------------------------------------

insert into sales.city (name, state_id) values ('Bethlehem', 494);
insert into sales.city (name, state_id) values ('Nuits-Saint-Georges', 966);
insert into sales.city (name, state_id) values ('Santo Niño', 772);
insert into sales.city (name, state_id) values ('Al Ḩazm', 676);
insert into sales.city (name, state_id) values ('Varāmīn', 984);
insert into sales.city (name, state_id) values ('Khenifra', 464);
insert into sales.city (name, state_id) values ('Orzesze', 190);
insert into sales.city (name, state_id) values ('As Sukhnah', 271);
insert into sales.city (name, state_id) values ('IJmuiden', 433);
insert into sales.city (name, state_id) values ('Pedro Betancourt', 748);
insert into sales.city (name, state_id) values ('Rzyki', 470);
insert into sales.city (name, state_id) values ('Águas de Lindóia', 217);
insert into sales.city (name, state_id) values ('Jelcz', 624);
insert into sales.city (name, state_id) values ('Sedan', 149);
insert into sales.city (name, state_id) values ('Banjarmasin', 144);
insert into sales.city (name, state_id) values ('Tifni', 109);
insert into sales.city (name, state_id) values ('Xiazhai', 759);
insert into sales.city (name, state_id) values ('Châu Thành', 15);
insert into sales.city (name, state_id) values ('Banī Walīd', 313);
insert into sales.city (name, state_id) values ('Soasio', 510);
insert into sales.city (name, state_id) values ('Nal’chik', 326);
insert into sales.city (name, state_id) values ('Carania', 349);
insert into sales.city (name, state_id) values ('Valmiera', 943);
insert into sales.city (name, state_id) values ('Sophia Antipolis', 780);
insert into sales.city (name, state_id) values ('Shalya', 435);
insert into sales.city (name, state_id) values ('Poddor’ye', 189);
insert into sales.city (name, state_id) values ('Ustynivka', 180);
insert into sales.city (name, state_id) values ('Goyty', 474);
insert into sales.city (name, state_id) values ('San Marcos', 498);
insert into sales.city (name, state_id) values ('Novyy', 649);
insert into sales.city (name, state_id) values ('Zwolle', 756);
insert into sales.city (name, state_id) values ('Dawwār Tīnjah', 918);
insert into sales.city (name, state_id) values ('Zgornje Pirniče', 981);
insert into sales.city (name, state_id) values ('Pulo', 451);
insert into sales.city (name, state_id) values ('Noginsk', 722);
insert into sales.city (name, state_id) values ('Elbasan', 991);
insert into sales.city (name, state_id) values ('Dongyong', 269);
insert into sales.city (name, state_id) values ('Elena', 901);
insert into sales.city (name, state_id) values ('Stockholm', 239);
insert into sales.city (name, state_id) values ('Zabaykal’sk', 351);
insert into sales.city (name, state_id) values ('Sinhyeon', 396);
insert into sales.city (name, state_id) values ('Parque Industrial', 481);
insert into sales.city (name, state_id) values ('Jacksonville', 119);
insert into sales.city (name, state_id) values ('Ikhtiman', 646);
insert into sales.city (name, state_id) values ('Araguaína', 512);
insert into sales.city (name, state_id) values ('Costeira do Pirajubae', 12);
insert into sales.city (name, state_id) values ('Sv. Ana v Slov. Goricah', 879);
insert into sales.city (name, state_id) values ('Chakou', 534);
insert into sales.city (name, state_id) values ('Pyrgetós', 751);
insert into sales.city (name, state_id) values ('Cabucgayan', 625);
insert into sales.city (name, state_id) values ('Yongping', 575);
insert into sales.city (name, state_id) values ('Faranah', 349);
insert into sales.city (name, state_id) values ('Sandakan', 393);
insert into sales.city (name, state_id) values ('Baz', 929);
insert into sales.city (name, state_id) values ('Manjakandriana', 832);
insert into sales.city (name, state_id) values ('Bronx', 22);
insert into sales.city (name, state_id) values ('Quintães', 49);
insert into sales.city (name, state_id) values ('Genzi', 689);
insert into sales.city (name, state_id) values ('Saddina', 208);
insert into sales.city (name, state_id) values ('Medvedok', 470);
insert into sales.city (name, state_id) values ('Fucha', 50);
insert into sales.city (name, state_id) values ('Fonseca', 673);
insert into sales.city (name, state_id) values ('Vilufushi', 973);
insert into sales.city (name, state_id) values ('Candelaria', 109);
insert into sales.city (name, state_id) values ('Brampton', 832);
insert into sales.city (name, state_id) values ('Morazán', 365);
insert into sales.city (name, state_id) values ('Protvino', 426);
insert into sales.city (name, state_id) values ('Parigi', 460);
insert into sales.city (name, state_id) values ('Beigong', 465);
insert into sales.city (name, state_id) values ('Mondoteko', 667);
insert into sales.city (name, state_id) values ('Sarilhos Grandes', 48);
insert into sales.city (name, state_id) values ('Gornyy', 710);
insert into sales.city (name, state_id) values ('Gudauta', 15);
insert into sales.city (name, state_id) values ('Lochovice', 275);
insert into sales.city (name, state_id) values ('Surgut', 601);
insert into sales.city (name, state_id) values ('Shuanghejiedao', 280);
insert into sales.city (name, state_id) values ('Créteil', 844);
insert into sales.city (name, state_id) values ('Malaya Dubna', 848);
insert into sales.city (name, state_id) values ('Angostura', 871);
insert into sales.city (name, state_id) values ('Casal', 375);
insert into sales.city (name, state_id) values ('Nagareyama', 378);
insert into sales.city (name, state_id) values ('Telengsari', 125);
insert into sales.city (name, state_id) values ('Rudong', 279);
insert into sales.city (name, state_id) values ('Baharly', 77);
insert into sales.city (name, state_id) values ('Su-dong', 969);
insert into sales.city (name, state_id) values ('Weixin', 651);
insert into sales.city (name, state_id) values ('Chýnov', 698);
insert into sales.city (name, state_id) values ('Pervomayskaya', 121);
insert into sales.city (name, state_id) values ('Sölvesborg', 647);
insert into sales.city (name, state_id) values ('Aemura', 723);
insert into sales.city (name, state_id) values ('Quebrada de Arena', 394);
insert into sales.city (name, state_id) values ('Juršinci', 600);
insert into sales.city (name, state_id) values ('Gorichevo', 214);
insert into sales.city (name, state_id) values ('Karlstad', 540);
insert into sales.city (name, state_id) values ('Orzesze', 788);
insert into sales.city (name, state_id) values ('Bemposta', 997);
insert into sales.city (name, state_id) values ('Skópelos', 169);
insert into sales.city (name, state_id) values ('Lyon', 79);
insert into sales.city (name, state_id) values ('Fengle', 848);
insert into sales.city (name, state_id) values ('Penengahan', 156);
insert into sales.city (name, state_id) values ('Kalāt-e Nāderī', 614);
insert into sales.city (name, state_id) values ('Armenia', 294);
insert into sales.city (name, state_id) values ('Gaotian', 738);
insert into sales.city (name, state_id) values ('Tây Đằng', 43);
insert into sales.city (name, state_id) values ('Nunleu', 999);
insert into sales.city (name, state_id) values ('Santa Cruz de Guacas', 211);
insert into sales.city (name, state_id) values ('Jatobá', 79);
insert into sales.city (name, state_id) values ('Ostankinskiy', 775);
insert into sales.city (name, state_id) values ('Piúma', 217);
insert into sales.city (name, state_id) values ('Torres Novas', 195);
insert into sales.city (name, state_id) values ('Raejeru', 222);
insert into sales.city (name, state_id) values ('Selce', 782);
insert into sales.city (name, state_id) values ('Knyaginino', 688);
insert into sales.city (name, state_id) values ('Uhniv', 300);
insert into sales.city (name, state_id) values ('Tlogocilik', 777);
insert into sales.city (name, state_id) values ('Pulopaya', 444);
insert into sales.city (name, state_id) values ('Pereira', 149);
insert into sales.city (name, state_id) values ('Loppi', 692);
insert into sales.city (name, state_id) values ('Phetchabun', 685);
insert into sales.city (name, state_id) values ('Puerto Plata', 939);
insert into sales.city (name, state_id) values ('Kanie', 998);
insert into sales.city (name, state_id) values ('Göteborg', 271);
insert into sales.city (name, state_id) values ('Kyzyl-Kyya', 687);
insert into sales.city (name, state_id) values ('Shuikou', 540);
insert into sales.city (name, state_id) values ('Honglu', 699);
insert into sales.city (name, state_id) values ('Oslo', 210);
insert into sales.city (name, state_id) values ('Mwembe', 848);
insert into sales.city (name, state_id) values ('Kumla', 477);
insert into sales.city (name, state_id) values ('Donggaocun', 570);
insert into sales.city (name, state_id) values ('Qiryat Shemona', 372);
insert into sales.city (name, state_id) values ('Baishan', 19);
insert into sales.city (name, state_id) values ('Sumy', 183);
insert into sales.city (name, state_id) values ('Balyaga', 941);
insert into sales.city (name, state_id) values ('Sandefjord', 623);
insert into sales.city (name, state_id) values ('Rivera', 191);
insert into sales.city (name, state_id) values ('Babantar', 430);
insert into sales.city (name, state_id) values ('Martanesh', 76);
insert into sales.city (name, state_id) values ('Sīnah', 776);
insert into sales.city (name, state_id) values ('Meylan', 32);
insert into sales.city (name, state_id) values ('Nampula', 367);
insert into sales.city (name, state_id) values ('Allen', 721);
insert into sales.city (name, state_id) values ('Caramuca', 29);
insert into sales.city (name, state_id) values ('Ibiporã', 394);
insert into sales.city (name, state_id) values ('Vilhena', 365);
insert into sales.city (name, state_id) values ('Troyes', 52);
insert into sales.city (name, state_id) values ('Bemposta', 410);
insert into sales.city (name, state_id) values ('Cikawung', 974);
insert into sales.city (name, state_id) values ('Santa Helena', 576);
insert into sales.city (name, state_id) values ('Marseille', 722);
insert into sales.city (name, state_id) values ('Sioah', 845);
insert into sales.city (name, state_id) values ('Blimbing', 230);
insert into sales.city (name, state_id) values ('Luniao', 820);
insert into sales.city (name, state_id) values ('Kavásilas', 281);
insert into sales.city (name, state_id) values ('Centre de Flacq', 654);
insert into sales.city (name, state_id) values ('Magadan', 394);
insert into sales.city (name, state_id) values ('Dashiren', 116);
insert into sales.city (name, state_id) values ('Heshui', 408);
insert into sales.city (name, state_id) values ('Carvalhos', 442);
insert into sales.city (name, state_id) values ('Dianshui', 879);
insert into sales.city (name, state_id) values ('San Antonio', 931);
insert into sales.city (name, state_id) values ('Zwettl', 317);
insert into sales.city (name, state_id) values ('Cannes', 594);
insert into sales.city (name, state_id) values ('Adolfo Lopez Mateos', 519);
insert into sales.city (name, state_id) values ('Campos', 103);
insert into sales.city (name, state_id) values ('Karangasem', 458);
insert into sales.city (name, state_id) values ('Kadudampit', 350);
insert into sales.city (name, state_id) values ('Wonorejo Dua', 666);
insert into sales.city (name, state_id) values ('Magburaka', 353);
insert into sales.city (name, state_id) values ('Patrída', 667);
insert into sales.city (name, state_id) values ('Bafatá', 454);
insert into sales.city (name, state_id) values ('Aranas Sur', 957);
insert into sales.city (name, state_id) values ('Yangzi Jianglu', 128);
insert into sales.city (name, state_id) values ('Malko Tŭrnovo', 281);
insert into sales.city (name, state_id) values ('Mawza‘', 431);
insert into sales.city (name, state_id) values ('Shaoxing', 252);
insert into sales.city (name, state_id) values ('Andrijaševci', 716);
insert into sales.city (name, state_id) values ('Kerkrade', 458);
insert into sales.city (name, state_id) values ('Xiaolong', 665);
insert into sales.city (name, state_id) values ('Baz', 180);
insert into sales.city (name, state_id) values ('Oliveira de Frades', 18);
insert into sales.city (name, state_id) values ('Ożarowice', 575);
insert into sales.city (name, state_id) values ('Sijiu', 491);
insert into sales.city (name, state_id) values ('Huaqiu', 186);
insert into sales.city (name, state_id) values ('Scranton', 13);
insert into sales.city (name, state_id) values ('Bachuan', 368);
insert into sales.city (name, state_id) values ('Bamnet Narong', 880);
insert into sales.city (name, state_id) values ('Bylym', 952);
insert into sales.city (name, state_id) values ('Baie-Saint-Paul', 205);
insert into sales.city (name, state_id) values ('Los Mangos', 642);
insert into sales.city (name, state_id) values ('Valdemarsvik', 73);
insert into sales.city (name, state_id) values ('San Bernardino', 602);
insert into sales.city (name, state_id) values ('Pospelikha', 390);
insert into sales.city (name, state_id) values ('Paranaguá', 911);
insert into sales.city (name, state_id) values ('Banjar Swastika', 984);
insert into sales.city (name, state_id) values ('Beloye', 749);
insert into sales.city (name, state_id) values ('Skanör', 669);
insert into sales.city (name, state_id) values ('Poitiers', 849);
insert into sales.city (name, state_id) values ('Tunduma', 402);
insert into sales.city (name, state_id) values ('Noramarg', 33);
insert into sales.city (name, state_id) values ('Bački Petrovac', 992);
insert into sales.city (name, state_id) values ('Santa Cruz da Graciosa', 120);
insert into sales.city (name, state_id) values ('Pyatovskiy', 578);
insert into sales.city (name, state_id) values ('Sayansk', 934);
insert into sales.city (name, state_id) values ('Vällingby', 850);
insert into sales.city (name, state_id) values ('Kombolcha', 508);
insert into sales.city (name, state_id) values ('Sanankerto', 514);
insert into sales.city (name, state_id) values ('Kępno', 154);
insert into sales.city (name, state_id) values ('El Paso', 340);
insert into sales.city (name, state_id) values ('Huaicheng', 607);
insert into sales.city (name, state_id) values ('Thị Trấn Quế', 671);
insert into sales.city (name, state_id) values ('L''viv', 902);
insert into sales.city (name, state_id) values ('Atalaia', 809);
insert into sales.city (name, state_id) values ('Rio Largo', 149);
insert into sales.city (name, state_id) values ('Severka', 679);
insert into sales.city (name, state_id) values ('Liaoyang', 216);
insert into sales.city (name, state_id) values ('Jembatandua', 730);
insert into sales.city (name, state_id) values ('Lydenburg', 772);
insert into sales.city (name, state_id) values ('Abiko', 633);
insert into sales.city (name, state_id) values ('Chai Badan', 981);
insert into sales.city (name, state_id) values ('Novoarkhanhel’s’k', 728);
insert into sales.city (name, state_id) values ('Jinqiao', 357);
insert into sales.city (name, state_id) values ('Cambita Garabitos', 247);
insert into sales.city (name, state_id) values ('Tianhekou', 651);
insert into sales.city (name, state_id) values ('Nangewer', 298);
insert into sales.city (name, state_id) values ('Xing’an', 113);
insert into sales.city (name, state_id) values ('Sävedalen', 338);
insert into sales.city (name, state_id) values ('Cambuga', 18);
insert into sales.city (name, state_id) values ('Mapusagafou', 15);
insert into sales.city (name, state_id) values ('Trinity Ville', 523);
insert into sales.city (name, state_id) values ('Tycheró', 100);
insert into sales.city (name, state_id) values ('Lianhe', 217);
insert into sales.city (name, state_id) values ('Lípa', 497);
insert into sales.city (name, state_id) values ('Pesnica pri Mariboru', 709);
insert into sales.city (name, state_id) values ('Ampasimanolotra', 519);
insert into sales.city (name, state_id) values ('Inawashiro', 669);
insert into sales.city (name, state_id) values ('Caijiang', 456);
insert into sales.city (name, state_id) values ('Liangdong', 204);
insert into sales.city (name, state_id) values ('Awjilah', 678);
insert into sales.city (name, state_id) values ('Ban Na San', 845);
insert into sales.city (name, state_id) values ('Estância', 825);
insert into sales.city (name, state_id) values ('Inya', 365);
insert into sales.city (name, state_id) values ('Guadalupe', 483);
insert into sales.city (name, state_id) values ('Paris 12', 210);
insert into sales.city (name, state_id) values ('Pajeksan', 492);
insert into sales.city (name, state_id) values ('Yakovlevo', 27);
insert into sales.city (name, state_id) values ('Cisitu', 670);
insert into sales.city (name, state_id) values ('Tékane', 610);
insert into sales.city (name, state_id) values ('Velyki Mezhyrichi', 828);
insert into sales.city (name, state_id) values ('Yong’an', 463);
insert into sales.city (name, state_id) values ('Lévis', 328);
insert into sales.city (name, state_id) values ('Aracati', 101);
insert into sales.city (name, state_id) values ('Kagoro', 908);
insert into sales.city (name, state_id) values ('Gunan', 49);
insert into sales.city (name, state_id) values ('Lomboy', 165);
insert into sales.city (name, state_id) values ('Sarandi', 255);
insert into sales.city (name, state_id) values ('Jayawangi', 356);
insert into sales.city (name, state_id) values ('Jingyu', 687);
insert into sales.city (name, state_id) values ('Lycksele', 569);
insert into sales.city (name, state_id) values ('Yangdun', 213);
insert into sales.city (name, state_id) values ('Klagenfurt am Wörthersee', 881);
insert into sales.city (name, state_id) values ('Heka', 71);
insert into sales.city (name, state_id) values ('Prachamtakham', 234);
insert into sales.city (name, state_id) values ('Ozërsk', 667);
insert into sales.city (name, state_id) values ('Nice', 501);
insert into sales.city (name, state_id) values ('Nanlang', 338);
insert into sales.city (name, state_id) values ('Tojal', 502);
insert into sales.city (name, state_id) values ('Majiadu', 26);
insert into sales.city (name, state_id) values ('Tsant', 663);
insert into sales.city (name, state_id) values ('Tampa', 869);
insert into sales.city (name, state_id) values ('Kousséri', 184);
insert into sales.city (name, state_id) values ('Savalou', 250);
insert into sales.city (name, state_id) values ('Kokagax', 577);
insert into sales.city (name, state_id) values ('Youngstown', 586);
insert into sales.city (name, state_id) values ('Atlanta', 522);
insert into sales.city (name, state_id) values ('Mainang', 811);
insert into sales.city (name, state_id) values ('Xinsheng', 288);
insert into sales.city (name, state_id) values ('Emin', 148);
insert into sales.city (name, state_id) values ('Kyllíni', 703);
insert into sales.city (name, state_id) values ('Llazicë', 361);
insert into sales.city (name, state_id) values ('Monte Francisco', 754);
insert into sales.city (name, state_id) values ('Šuto Orizare', 3);
insert into sales.city (name, state_id) values ('Arendal', 168);
insert into sales.city (name, state_id) values ('Jablonné nad Orlicí', 525);
insert into sales.city (name, state_id) values ('General Lavalle', 367);
insert into sales.city (name, state_id) values ('Guandu', 135);
insert into sales.city (name, state_id) values ('Pantang', 873);
insert into sales.city (name, state_id) values ('Bystra', 7);
insert into sales.city (name, state_id) values ('Miyang', 917);
insert into sales.city (name, state_id) values ('Kertai', 294);
insert into sales.city (name, state_id) values ('Vónitsa', 900);
insert into sales.city (name, state_id) values ('Xiahan', 583);
insert into sales.city (name, state_id) values ('Parumaan', 566);
insert into sales.city (name, state_id) values ('Bayan Tuohai', 607);
insert into sales.city (name, state_id) values ('Pato Branco', 364);
insert into sales.city (name, state_id) values ('Pindi Gheb', 677);
insert into sales.city (name, state_id) values ('Szolnok', 809);
insert into sales.city (name, state_id) values ('Kedungharjo', 441);
insert into sales.city (name, state_id) values ('Pakel', 633);
insert into sales.city (name, state_id) values ('Limbaži', 486);
insert into sales.city (name, state_id) values ('Sangba', 149);
insert into sales.city (name, state_id) values ('Nieuwegein', 200);
insert into sales.city (name, state_id) values ('Sidaurip', 323);
insert into sales.city (name, state_id) values ('Matam', 266);
insert into sales.city (name, state_id) values ('Sentani', 555);
insert into sales.city (name, state_id) values ('Aco', 118);
insert into sales.city (name, state_id) values ('Kaeng Khoi', 989);
insert into sales.city (name, state_id) values ('Vaggeryd', 662);
insert into sales.city (name, state_id) values ('Mekarsari', 643);
insert into sales.city (name, state_id) values ('Panenjoan', 69);
insert into sales.city (name, state_id) values ('Aguiar da Beira', 997);
insert into sales.city (name, state_id) values ('Málaga', 538);
insert into sales.city (name, state_id) values ('Wonokromo', 545);
insert into sales.city (name, state_id) values ('Ambian', 822);
insert into sales.city (name, state_id) values ('Huicungo', 276);
insert into sales.city (name, state_id) values ('Guangchen', 207);
insert into sales.city (name, state_id) values ('Yefimovskiy', 311);
insert into sales.city (name, state_id) values ('Magoúla', 115);
insert into sales.city (name, state_id) values ('Sanchahe', 380);
insert into sales.city (name, state_id) values ('Amirdzhan', 321);
insert into sales.city (name, state_id) values ('Mianay', 334);
insert into sales.city (name, state_id) values ('Ocongate', 191);
insert into sales.city (name, state_id) values ('Houston', 223);
insert into sales.city (name, state_id) values ('Hatavch', 38);
insert into sales.city (name, state_id) values ('Shanghudi', 999);
insert into sales.city (name, state_id) values ('Fengcheng', 777);
insert into sales.city (name, state_id) values ('Marseille', 826);
insert into sales.city (name, state_id) values ('Tužno', 459);
insert into sales.city (name, state_id) values ('Sakai', 284);
insert into sales.city (name, state_id) values ('Dukla', 903);
insert into sales.city (name, state_id) values ('Ternovka', 847);
insert into sales.city (name, state_id) values ('La Uvita', 415);
insert into sales.city (name, state_id) values ('Lanas', 599);
insert into sales.city (name, state_id) values ('Pasrukrajan Satu', 174);
insert into sales.city (name, state_id) values ('Garawati', 94);
insert into sales.city (name, state_id) values ('Leer', 960);
insert into sales.city (name, state_id) values ('Gapan', 54);
insert into sales.city (name, state_id) values ('Gjoa Haven', 48);
insert into sales.city (name, state_id) values ('Shaft', 146);
insert into sales.city (name, state_id) values ('Thongwa', 559);
insert into sales.city (name, state_id) values ('Boli', 109);
insert into sales.city (name, state_id) values ('Nishinoomote', 563);
insert into sales.city (name, state_id) values ('Padangbai', 379);
insert into sales.city (name, state_id) values ('Sifangxi', 815);
insert into sales.city (name, state_id) values ('Gaojingzhuang', 32);
insert into sales.city (name, state_id) values ('Sulęcin', 56);
insert into sales.city (name, state_id) values ('Sansheng', 541);
insert into sales.city (name, state_id) values ('Lenger', 280);
insert into sales.city (name, state_id) values ('Xihe', 496);
insert into sales.city (name, state_id) values ('Tha Mai', 465);
insert into sales.city (name, state_id) values ('Narutochō-mitsuishi', 328);
insert into sales.city (name, state_id) values ('Qiuchuan', 742);
insert into sales.city (name, state_id) values ('San Bernardino', 903);
insert into sales.city (name, state_id) values ('Paraíso das Águas', 587);
insert into sales.city (name, state_id) values ('Kidričevo', 830);
insert into sales.city (name, state_id) values ('San Jose', 294);
insert into sales.city (name, state_id) values ('Yiqian', 706);
insert into sales.city (name, state_id) values ('Huizhou', 413);
insert into sales.city (name, state_id) values ('Moreira de Geraz do Lima', 663);
insert into sales.city (name, state_id) values ('Las Vegas', 651);
insert into sales.city (name, state_id) values ('Kuala Lumpur', 276);
insert into sales.city (name, state_id) values ('Rettikhovka', 382);
insert into sales.city (name, state_id) values ('Abomey-Calavi', 266);
insert into sales.city (name, state_id) values ('Lazaro Cardenas', 414);
insert into sales.city (name, state_id) values ('Spétses', 171);
insert into sales.city (name, state_id) values ('Yanjiatai', 954);
insert into sales.city (name, state_id) values ('Besuk Selatan', 233);
insert into sales.city (name, state_id) values ('Monamon', 442);
insert into sales.city (name, state_id) values ('Companhia de Baixo', 596);
insert into sales.city (name, state_id) values ('Las Minas', 405);
insert into sales.city (name, state_id) values ('Wonokromo', 379);
insert into sales.city (name, state_id) values ('Xiaolong', 613);
insert into sales.city (name, state_id) values ('Banjar Kertasari', 557);
insert into sales.city (name, state_id) values ('Araçoiaba da Serra', 118);
insert into sales.city (name, state_id) values ('Marietta', 904);
insert into sales.city (name, state_id) values ('Renchaoxi', 204);
insert into sales.city (name, state_id) values ('Enjitsu', 575);
insert into sales.city (name, state_id) values ('Nancun', 308);
insert into sales.city (name, state_id) values ('Jiadingzhen', 705);
insert into sales.city (name, state_id) values ('Landi Kotal', 756);
insert into sales.city (name, state_id) values ('Iturama', 219);
insert into sales.city (name, state_id) values ('Pakxong', 361);
insert into sales.city (name, state_id) values ('Sheshan', 853);
insert into sales.city (name, state_id) values ('Changgou', 726);
insert into sales.city (name, state_id) values ('Batan', 716);
insert into sales.city (name, state_id) values ('Liangdang Chengguanzhen', 449);
insert into sales.city (name, state_id) values ('Megáli Khóra', 453);
insert into sales.city (name, state_id) values ('Nangerang', 191);
insert into sales.city (name, state_id) values ('Troitskoye', 131);
insert into sales.city (name, state_id) values ('Puan', 585);
insert into sales.city (name, state_id) values ('Adolfo Lopez Mateos', 196);
insert into sales.city (name, state_id) values ('Stoczek Łukowski', 877);
insert into sales.city (name, state_id) values ('Głogów Małopolski', 779);
insert into sales.city (name, state_id) values ('Chame', 657);
insert into sales.city (name, state_id) values ('Marisgama', 591);
insert into sales.city (name, state_id) values ('Geputan', 3);
insert into sales.city (name, state_id) values ('Kremenets’', 930);
insert into sales.city (name, state_id) values ('Strenči', 671);
insert into sales.city (name, state_id) values ('Marína', 286);
insert into sales.city (name, state_id) values ('Novokubansk', 323);
insert into sales.city (name, state_id) values ('Hotaka', 529);
insert into sales.city (name, state_id) values ('Oka', 959);
insert into sales.city (name, state_id) values ('Boniewo', 506);
insert into sales.city (name, state_id) values ('Illkirch-Graffenstaden', 389);
insert into sales.city (name, state_id) values ('Agrínio', 43);
insert into sales.city (name, state_id) values ('Nýřany', 950);
insert into sales.city (name, state_id) values ('Ocuviri', 146);
insert into sales.city (name, state_id) values ('Syrostan', 932);
insert into sales.city (name, state_id) values ('Songlong', 152);
insert into sales.city (name, state_id) values ('Naguilian', 149);
insert into sales.city (name, state_id) values ('Huaranchal', 112);
insert into sales.city (name, state_id) values ('Mairana', 866);
insert into sales.city (name, state_id) values ('Ban Phaeo', 85);
insert into sales.city (name, state_id) values ('Novomichurinsk', 712);
insert into sales.city (name, state_id) values ('Gamboula', 236);
insert into sales.city (name, state_id) values ('Łapczyca', 962);
insert into sales.city (name, state_id) values ('Xihongmen', 482);
insert into sales.city (name, state_id) values ('Karangsuko', 530);
insert into sales.city (name, state_id) values ('Montonggamang', 714);
insert into sales.city (name, state_id) values ('Baisha', 534);
insert into sales.city (name, state_id) values ('Cimo de Vila', 305);
insert into sales.city (name, state_id) values ('Avlónas', 224);
insert into sales.city (name, state_id) values ('Ribnica na Pohorju', 37);
insert into sales.city (name, state_id) values ('Alta Gracia', 75);
insert into sales.city (name, state_id) values ('Longcang', 456);
insert into sales.city (name, state_id) values ('Walichnowy', 93);
insert into sales.city (name, state_id) values ('Arys', 568);
insert into sales.city (name, state_id) values ('Köln', 524);
insert into sales.city (name, state_id) values ('Guadalupe', 948);
insert into sales.city (name, state_id) values ('Buchanan', 38);
insert into sales.city (name, state_id) values ('El Coco', 600);
insert into sales.city (name, state_id) values ('Xiaocun', 122);
insert into sales.city (name, state_id) values ('Cícero Dantas', 317);
insert into sales.city (name, state_id) values ('Magisterial', 153);
insert into sales.city (name, state_id) values ('Berlín', 489);
insert into sales.city (name, state_id) values ('Xiangride', 341);
insert into sales.city (name, state_id) values ('East Migpulao', 851);
insert into sales.city (name, state_id) values ('Maykopskoye', 132);
insert into sales.city (name, state_id) values ('Shilipu', 836);
insert into sales.city (name, state_id) values ('Parada de Pinhão', 754);
insert into sales.city (name, state_id) values ('Livorno', 218);
insert into sales.city (name, state_id) values ('Foxrock', 592);
insert into sales.city (name, state_id) values ('Porto Real', 41);
insert into sales.city (name, state_id) values ('Camrose', 506);
insert into sales.city (name, state_id) values ('El Monte', 195);
insert into sales.city (name, state_id) values ('Rajal Norte', 805);
insert into sales.city (name, state_id) values ('Mozhga', 871);
insert into sales.city (name, state_id) values ('Anchang', 574);
insert into sales.city (name, state_id) values ('Willowmore', 862);
insert into sales.city (name, state_id) values ('Wonosari', 292);
insert into sales.city (name, state_id) values ('Daitōchō', 644);
insert into sales.city (name, state_id) values ('Huaminglou', 922);
insert into sales.city (name, state_id) values ('Arnaía', 283);
insert into sales.city (name, state_id) values ('Palmira', 14);
insert into sales.city (name, state_id) values ('Zhavoronki', 850);
insert into sales.city (name, state_id) values ('Sāh', 212);
insert into sales.city (name, state_id) values ('Jianxincun', 978);
insert into sales.city (name, state_id) values ('Houxixi', 371);
insert into sales.city (name, state_id) values ('Qā’en', 367);
insert into sales.city (name, state_id) values ('Castelo de Vide', 255);
insert into sales.city (name, state_id) values ('Mongo', 657);
insert into sales.city (name, state_id) values ('Weiyuan', 512);
insert into sales.city (name, state_id) values ('Lakota', 628);
insert into sales.city (name, state_id) values ('Negararatu', 456);
insert into sales.city (name, state_id) values ('Vila Franca das Naves', 922);
insert into sales.city (name, state_id) values ('Bila Tserkva', 362);
insert into sales.city (name, state_id) values ('Camgyai', 467);
insert into sales.city (name, state_id) values ('Bagneux', 415);
insert into sales.city (name, state_id) values ('Fershampenuaz', 377);
insert into sales.city (name, state_id) values ('Igpit', 660);
insert into sales.city (name, state_id) values ('Zhushan', 544);
insert into sales.city (name, state_id) values ('Otterburn Park', 647);
insert into sales.city (name, state_id) values ('Bamiantong', 109);
insert into sales.city (name, state_id) values ('Alingsås', 458);
insert into sales.city (name, state_id) values ('Kota Bharu', 75);
insert into sales.city (name, state_id) values ('Puricay', 241);
insert into sales.city (name, state_id) values ('Notre Dame', 385);
insert into sales.city (name, state_id) values ('Seleuš', 984);
insert into sales.city (name, state_id) values ('La Rioja', 97);
insert into sales.city (name, state_id) values ('Kradinan', 490);
insert into sales.city (name, state_id) values ('Bantar Tengah', 681);
insert into sales.city (name, state_id) values ('Novoarkhanhel’s’k', 914);
insert into sales.city (name, state_id) values ('Shikou', 390);
insert into sales.city (name, state_id) values ('Inawashiro', 391);
insert into sales.city (name, state_id) values ('Libas', 394);
insert into sales.city (name, state_id) values ('Richmond', 944);
insert into sales.city (name, state_id) values ('Buliu', 841);
insert into sales.city (name, state_id) values ('Ágios Stéfanos', 212);
insert into sales.city (name, state_id) values ('Karakulino', 356);
insert into sales.city (name, state_id) values ('Baryshivka', 582);
insert into sales.city (name, state_id) values ('Anhua', 995);
insert into sales.city (name, state_id) values ('Minas de Marcona', 296);
insert into sales.city (name, state_id) values ('Nangahale', 337);
insert into sales.city (name, state_id) values ('Cholet', 53);
insert into sales.city (name, state_id) values ('Três Corações', 719);
insert into sales.city (name, state_id) values ('Hedi', 366);
insert into sales.city (name, state_id) values ('Gällivare', 430);
insert into sales.city (name, state_id) values ('Satun', 424);
insert into sales.city (name, state_id) values ('Zhonghuopu', 115);
insert into sales.city (name, state_id) values ('Jardia', 743);
insert into sales.city (name, state_id) values ('Guachetá', 232);
insert into sales.city (name, state_id) values ('Pingtian', 391);
insert into sales.city (name, state_id) values ('Touba', 459);
insert into sales.city (name, state_id) values ('Yangjiafang', 945);
insert into sales.city (name, state_id) values ('Yangxunqiao', 72);
insert into sales.city (name, state_id) values ('Miyakonojō', 197);
insert into sales.city (name, state_id) values ('Psychikó', 899);
insert into sales.city (name, state_id) values ('Bošovice', 50);
insert into sales.city (name, state_id) values ('Utrecht', 199);
insert into sales.city (name, state_id) values ('Zangzhai', 891);
insert into sales.city (name, state_id) values ('Banjarmasin', 311);
insert into sales.city (name, state_id) values ('Kleszczów', 420);
insert into sales.city (name, state_id) values ('Mabuttal East', 217);
insert into sales.city (name, state_id) values ('Yamkino', 410);
insert into sales.city (name, state_id) values ('Orléans', 850);
insert into sales.city (name, state_id) values ('Xinglong', 742);
insert into sales.city (name, state_id) values ('Nikopol’', 383);
insert into sales.city (name, state_id) values ('Briceni', 395);
insert into sales.city (name, state_id) values ('Alençon', 898);
insert into sales.city (name, state_id) values ('Dukuhbadag', 396);
insert into sales.city (name, state_id) values ('Zhenqiao', 590);
insert into sales.city (name, state_id) values ('Shibukawa', 433);
insert into sales.city (name, state_id) values ('Changchuan', 688);
insert into sales.city (name, state_id) values ('Mundybash', 569);
insert into sales.city (name, state_id) values ('Jermuk', 377);
insert into sales.city (name, state_id) values ('Clonskeagh', 874);
insert into sales.city (name, state_id) values ('Aş Şafaqayn', 791);
insert into sales.city (name, state_id) values ('Wukang', 771);
insert into sales.city (name, state_id) values ('Palanas', 408);
insert into sales.city (name, state_id) values ('Bria', 831);
insert into sales.city (name, state_id) values ('Muhoroni', 693);
insert into sales.city (name, state_id) values ('Norrköping', 869);
insert into sales.city (name, state_id) values ('Boca Raton', 771);
insert into sales.city (name, state_id) values ('Tha Bo', 211);
insert into sales.city (name, state_id) values ('Owando', 825);
insert into sales.city (name, state_id) values ('Mangas', 634);
insert into sales.city (name, state_id) values ('Krasnyye Barrikady', 944);
insert into sales.city (name, state_id) values ('Stockholm', 896);
insert into sales.city (name, state_id) values ('Nueva Requena', 803);
insert into sales.city (name, state_id) values ('Barishāl', 839);
insert into sales.city (name, state_id) values ('Garden Grove', 877);
insert into sales.city (name, state_id) values ('Masinloc', 652);
insert into sales.city (name, state_id) values ('Zaraza', 274);
insert into sales.city (name, state_id) values ('Sedinginan', 165);
insert into sales.city (name, state_id) values ('Karanganyar', 267);
insert into sales.city (name, state_id) values ('Charleston', 746);
insert into sales.city (name, state_id) values ('Lutou', 853);
insert into sales.city (name, state_id) values ('Denton', 561);
insert into sales.city (name, state_id) values ('Penglai', 636);
insert into sales.city (name, state_id) values ('Hamburg Harvestehude', 718);
insert into sales.city (name, state_id) values ('Czerwonak', 545);
insert into sales.city (name, state_id) values ('Kudang', 909);
insert into sales.city (name, state_id) values ('Taouima', 95);
insert into sales.city (name, state_id) values ('Huangzhuang', 495);
insert into sales.city (name, state_id) values ('Orlovskiy', 988);
insert into sales.city (name, state_id) values ('Sirte', 256);
insert into sales.city (name, state_id) values ('Xingquan', 793);
insert into sales.city (name, state_id) values ('Larvik', 794);
insert into sales.city (name, state_id) values ('Yangshan', 293);
insert into sales.city (name, state_id) values ('Dong’an', 171);
insert into sales.city (name, state_id) values ('Dangshun', 423);
insert into sales.city (name, state_id) values ('Piotrków Kujawski', 729);
insert into sales.city (name, state_id) values ('Yarabamba', 309);
insert into sales.city (name, state_id) values ('Modimolle', 212);
insert into sales.city (name, state_id) values ('Qiting', 83);
insert into sales.city (name, state_id) values ('Kokofata', 211);
insert into sales.city (name, state_id) values ('Töysä', 744);
insert into sales.city (name, state_id) values ('Centralniy', 392);
insert into sales.city (name, state_id) values ('Rancamaya', 238);
insert into sales.city (name, state_id) values ('Shirokaya Rechka', 295);
insert into sales.city (name, state_id) values ('Sanbao', 318);
insert into sales.city (name, state_id) values ('Fram', 1000);
insert into sales.city (name, state_id) values ('Eshowe', 932);
insert into sales.city (name, state_id) values ('Palapye', 967);
insert into sales.city (name, state_id) values ('Fontana', 884);
insert into sales.city (name, state_id) values ('Bhamo', 749);
insert into sales.city (name, state_id) values ('Fonte de Angeão', 790);
insert into sales.city (name, state_id) values ('Emmen', 675);
insert into sales.city (name, state_id) values ('Quận Tân Phú', 74);
insert into sales.city (name, state_id) values ('Puerto Boyacá', 902);
insert into sales.city (name, state_id) values ('Omoku', 825);
insert into sales.city (name, state_id) values ('Ash Shajarah', 492);
insert into sales.city (name, state_id) values ('Berezivka', 166);
insert into sales.city (name, state_id) values ('Benniu', 680);
insert into sales.city (name, state_id) values ('Llalli', 785);
insert into sales.city (name, state_id) values ('Satowebrang', 487);
insert into sales.city (name, state_id) values ('Yolöten', 276);
insert into sales.city (name, state_id) values ('Taoyuan', 3);
insert into sales.city (name, state_id) values ('Salvacion', 394);
insert into sales.city (name, state_id) values ('Minneapolis', 617);
insert into sales.city (name, state_id) values ('Kungshamn', 575);
insert into sales.city (name, state_id) values ('Sukadana', 139);
insert into sales.city (name, state_id) values ('Groningen', 329);
insert into sales.city (name, state_id) values ('Navegantes', 530);
insert into sales.city (name, state_id) values ('Klampok', 73);
insert into sales.city (name, state_id) values ('Raciąż', 734);
insert into sales.city (name, state_id) values ('Vostryakovo', 759);
insert into sales.city (name, state_id) values ('Hrob', 207);
insert into sales.city (name, state_id) values ('Sa''dah', 686);
insert into sales.city (name, state_id) values ('Checacupe', 733);
insert into sales.city (name, state_id) values ('Maibu', 119);
insert into sales.city (name, state_id) values ('Palaiochóri', 583);
insert into sales.city (name, state_id) values ('Foros da Catrapona', 531);
insert into sales.city (name, state_id) values ('Alangalang', 695);
insert into sales.city (name, state_id) values ('Huji', 360);
insert into sales.city (name, state_id) values ('Mohelno', 193);
insert into sales.city (name, state_id) values ('Hamburg', 716);
insert into sales.city (name, state_id) values ('Cerrito', 386);
insert into sales.city (name, state_id) values ('Cirateun', 797);
insert into sales.city (name, state_id) values ('Bonavista', 653);
insert into sales.city (name, state_id) values ('Curug', 98);
insert into sales.city (name, state_id) values ('Hněvotín', 680);
insert into sales.city (name, state_id) values ('Bago City', 48);
insert into sales.city (name, state_id) values ('Taphan Hin', 944);
insert into sales.city (name, state_id) values ('Campoalegre', 415);
insert into sales.city (name, state_id) values ('Grenoble', 544);
insert into sales.city (name, state_id) values ('Krajan Satu', 230);
insert into sales.city (name, state_id) values ('Liangshuijing', 39);
insert into sales.city (name, state_id) values ('San Pedro', 222);
insert into sales.city (name, state_id) values ('Marmashen', 719);
insert into sales.city (name, state_id) values ('Hegeng', 530);
insert into sales.city (name, state_id) values ('Pallasovka', 122);
insert into sales.city (name, state_id) values ('Bom Jesus da Lapa', 389);
insert into sales.city (name, state_id) values ('Jinzhou', 595);
insert into sales.city (name, state_id) values ('Ad Dīs ash Sharqīyah', 185);
insert into sales.city (name, state_id) values ('Bassar', 1);
insert into sales.city (name, state_id) values ('Parry Sound', 141);
insert into sales.city (name, state_id) values ('Nila Dua', 441);
insert into sales.city (name, state_id) values ('Huddinge', 77);
insert into sales.city (name, state_id) values ('Conceição da Barra', 978);
insert into sales.city (name, state_id) values ('Ibirataia', 664);
insert into sales.city (name, state_id) values ('Villa María', 66);
insert into sales.city (name, state_id) values ('Antonina', 741);
insert into sales.city (name, state_id) values ('San Vicente', 371);
insert into sales.city (name, state_id) values ('Obuasi', 508);
insert into sales.city (name, state_id) values ('Esquipulas Palo Gordo', 400);
insert into sales.city (name, state_id) values ('Shikhazany', 607);
insert into sales.city (name, state_id) values ('Valinhos', 554);
insert into sales.city (name, state_id) values ('Fushë-Muhurr', 253);
insert into sales.city (name, state_id) values ('Ampelgading', 396);
insert into sales.city (name, state_id) values ('Isfahan', 8);
insert into sales.city (name, state_id) values ('Ostrowsko', 754);
insert into sales.city (name, state_id) values ('Kiviõli', 544);
insert into sales.city (name, state_id) values ('Boca de Uchire', 119);
insert into sales.city (name, state_id) values ('El Cocuy', 466);
insert into sales.city (name, state_id) values ('Sari', 238);
insert into sales.city (name, state_id) values ('Hajoho', 588);
insert into sales.city (name, state_id) values ('Turbiv', 858);
insert into sales.city (name, state_id) values ('Mosty', 97);
insert into sales.city (name, state_id) values ('Aksarka', 248);
insert into sales.city (name, state_id) values ('Geita', 468);
insert into sales.city (name, state_id) values ('Nguluhan', 63);
insert into sales.city (name, state_id) values ('Zaokskiy', 187);
insert into sales.city (name, state_id) values ('Natonin', 771);
insert into sales.city (name, state_id) values ('Devin', 119);
insert into sales.city (name, state_id) values ('Litan', 983);
insert into sales.city (name, state_id) values ('Oni', 918);
insert into sales.city (name, state_id) values ('Ludishan', 811);
insert into sales.city (name, state_id) values ('Shicong', 674);
insert into sales.city (name, state_id) values ('Nizhniy Chir', 687);
insert into sales.city (name, state_id) values ('Phu Khiao', 749);
insert into sales.city (name, state_id) values ('Caucasia', 271);
insert into sales.city (name, state_id) values ('Kajanan', 730);
insert into sales.city (name, state_id) values ('Damnoen Saduak', 515);
insert into sales.city (name, state_id) values ('Nanbin', 511);
insert into sales.city (name, state_id) values ('Bantar Tengah', 816);
insert into sales.city (name, state_id) values ('Nowe Grocholice', 189);
insert into sales.city (name, state_id) values ('Pétange', 158);
insert into sales.city (name, state_id) values ('Kalibunder', 143);
insert into sales.city (name, state_id) values ('Santa Elena', 395);
insert into sales.city (name, state_id) values ('Kihancha', 287);
insert into sales.city (name, state_id) values ('Carcassonne', 291);
insert into sales.city (name, state_id) values ('Darpas', 910);
insert into sales.city (name, state_id) values ('Folques', 11);
insert into sales.city (name, state_id) values ('Buritizeiro', 709);
insert into sales.city (name, state_id) values ('Ciseuseupan', 909);
insert into sales.city (name, state_id) values ('Gunungjulang', 911);
insert into sales.city (name, state_id) values ('Sandefjord', 90);
insert into sales.city (name, state_id) values ('Muaralembu', 852);
insert into sales.city (name, state_id) values ('Shiki', 791);
insert into sales.city (name, state_id) values ('Areado', 326);
insert into sales.city (name, state_id) values ('Reims', 904);
insert into sales.city (name, state_id) values ('Olival', 833);
insert into sales.city (name, state_id) values ('San Roque', 546);
insert into sales.city (name, state_id) values ('Venda do Alcaide', 128);
insert into sales.city (name, state_id) values ('Palcamayo', 612);
insert into sales.city (name, state_id) values ('Tānk', 115);
insert into sales.city (name, state_id) values ('Sorol', 765);
insert into sales.city (name, state_id) values ('Zhangping', 310);
insert into sales.city (name, state_id) values ('Mloko', 95);
insert into sales.city (name, state_id) values ('Hengshan', 355);
insert into sales.city (name, state_id) values ('Mengla', 623);
insert into sales.city (name, state_id) values ('El Ángel', 43);
insert into sales.city (name, state_id) values ('Jiangshan', 571);
insert into sales.city (name, state_id) values ('Coelho Neto', 689);
insert into sales.city (name, state_id) values ('Yanacancha', 754);
insert into sales.city (name, state_id) values ('Tarqūmyā', 219);
insert into sales.city (name, state_id) values ('Sindong', 976);
insert into sales.city (name, state_id) values ('Spasskoye-Lutovinovo', 488);
insert into sales.city (name, state_id) values ('São Paio de Seide', 718);
insert into sales.city (name, state_id) values ('Manna', 190);
insert into sales.city (name, state_id) values ('Guayaquil', 618);
insert into sales.city (name, state_id) values ('Onega', 41);
insert into sales.city (name, state_id) values ('Antipino', 242);
insert into sales.city (name, state_id) values ('Bao’an', 326);
insert into sales.city (name, state_id) values ('Tucuruí', 384);
insert into sales.city (name, state_id) values ('Miami', 573);
insert into sales.city (name, state_id) values ('Xingou', 996);
insert into sales.city (name, state_id) values ('Tynne', 810);
insert into sales.city (name, state_id) values ('At Tall al Kabīr', 697);
insert into sales.city (name, state_id) values ('Talas', 61);
insert into sales.city (name, state_id) values ('Gaokan', 952);
insert into sales.city (name, state_id) values ('Duancun', 671);
insert into sales.city (name, state_id) values ('Pau', 814);
insert into sales.city (name, state_id) values ('Midoun', 88);
insert into sales.city (name, state_id) values ('Yong’an', 25);
insert into sales.city (name, state_id) values ('Anyu', 741);
insert into sales.city (name, state_id) values ('Nankou', 35);
insert into sales.city (name, state_id) values ('Namie', 1000);
insert into sales.city (name, state_id) values ('Merritt', 790);
insert into sales.city (name, state_id) values ('Putukrejo', 621);
insert into sales.city (name, state_id) values ('Shuren', 63);
insert into sales.city (name, state_id) values ('Yongfeng', 743);
insert into sales.city (name, state_id) values ('Port-Vila', 327);
insert into sales.city (name, state_id) values ('Dazhigu', 8);
insert into sales.city (name, state_id) values ('Richmond', 155);
insert into sales.city (name, state_id) values ('Xagqu', 119);
insert into sales.city (name, state_id) values ('Pietà', 913);
insert into sales.city (name, state_id) values ('Uusikaupunki', 98);
insert into sales.city (name, state_id) values ('Medalem', 206);
insert into sales.city (name, state_id) values ('Freixo de Numão', 922);
insert into sales.city (name, state_id) values ('Pan-an', 742);
insert into sales.city (name, state_id) values ('Żórawina', 8);
insert into sales.city (name, state_id) values ('Aihua', 700);
insert into sales.city (name, state_id) values ('Mons', 34);
insert into sales.city (name, state_id) values ('Bangkok', 802);
insert into sales.city (name, state_id) values ('Amurzet', 539);
insert into sales.city (name, state_id) values ('Arroteia', 537);
insert into sales.city (name, state_id) values ('Heishui', 413);
insert into sales.city (name, state_id) values ('Alvega', 531);
insert into sales.city (name, state_id) values ('Otrado-Kubanskoye', 956);
insert into sales.city (name, state_id) values ('Rtyně v Podkrkonoší', 788);
insert into sales.city (name, state_id) values ('Challas', 644);
insert into sales.city (name, state_id) values ('Gawanan', 909);
insert into sales.city (name, state_id) values ('Likwatang Timur', 187);
insert into sales.city (name, state_id) values ('Tsaritsyno', 950);
insert into sales.city (name, state_id) values ('Mandesan', 163);
insert into sales.city (name, state_id) values ('Sol’-Iletsk', 24);
insert into sales.city (name, state_id) values ('Mirzāpur', 203);
insert into sales.city (name, state_id) values ('Sacapulas', 747);
insert into sales.city (name, state_id) values ('København', 596);
insert into sales.city (name, state_id) values ('Sagarejo', 49);
insert into sales.city (name, state_id) values ('Sasovo', 157);
insert into sales.city (name, state_id) values ('Tōkamachi', 924);
insert into sales.city (name, state_id) values ('Kaum', 205);
insert into sales.city (name, state_id) values ('Stockholm', 503);
insert into sales.city (name, state_id) values ('Vitrolles', 345);
insert into sales.city (name, state_id) values ('Forninho', 962);
insert into sales.city (name, state_id) values ('El Paso', 934);
insert into sales.city (name, state_id) values ('Doushaguan', 849);
insert into sales.city (name, state_id) values ('Zhifudao', 197);
insert into sales.city (name, state_id) values ('Bruxelles', 164);
insert into sales.city (name, state_id) values ('Pantai', 963);
insert into sales.city (name, state_id) values ('Ciénaga', 294);
insert into sales.city (name, state_id) values ('Matanog', 266);
insert into sales.city (name, state_id) values ('Staré Město', 568);
insert into sales.city (name, state_id) values ('Zhongying', 720);
insert into sales.city (name, state_id) values ('Yangxi', 206);
insert into sales.city (name, state_id) values ('Atlanta', 714);
insert into sales.city (name, state_id) values ('Legrada', 875);
insert into sales.city (name, state_id) values ('Victoria', 283);
insert into sales.city (name, state_id) values ('Novobeysugskaya', 213);
insert into sales.city (name, state_id) values ('Mikhaylov', 851);
insert into sales.city (name, state_id) values ('Trbovlje', 157);
insert into sales.city (name, state_id) values ('Estrada', 807);
insert into sales.city (name, state_id) values ('Heyin', 380);
insert into sales.city (name, state_id) values ('Sembon', 620);
insert into sales.city (name, state_id) values ('Simpang', 329);
insert into sales.city (name, state_id) values ('Zarqa', 561);
insert into sales.city (name, state_id) values ('Kota Bharu', 700);
insert into sales.city (name, state_id) values ('Liure', 194);
insert into sales.city (name, state_id) values ('Lancar', 687);
insert into sales.city (name, state_id) values ('Loujiadian', 872);
insert into sales.city (name, state_id) values ('Injīl', 377);
insert into sales.city (name, state_id) values ('Érd', 65);
insert into sales.city (name, state_id) values ('Murom', 264);
insert into sales.city (name, state_id) values ('Osasco', 360);
insert into sales.city (name, state_id) values ('Maurole', 834);
insert into sales.city (name, state_id) values ('Yujiawu', 684);
insert into sales.city (name, state_id) values ('Si Ma Cai', 555);
insert into sales.city (name, state_id) values ('Liangshuijing', 976);
insert into sales.city (name, state_id) values ('Pico da Pedra', 248);
insert into sales.city (name, state_id) values ('Tuwiri Wetan', 741);
insert into sales.city (name, state_id) values ('Sukowiryo', 319);
insert into sales.city (name, state_id) values ('Shilin', 31);
insert into sales.city (name, state_id) values ('Cimara', 951);
insert into sales.city (name, state_id) values ('Charlton', 134);
insert into sales.city (name, state_id) values ('San Ramón', 96);
insert into sales.city (name, state_id) values ('Tojeira', 965);
insert into sales.city (name, state_id) values ('Bobojong', 534);
insert into sales.city (name, state_id) values ('Polyarnyy', 927);
insert into sales.city (name, state_id) values ('Bweyogerere', 317);
insert into sales.city (name, state_id) values ('Kotlovka', 413);
insert into sales.city (name, state_id) values ('Kiev', 410);
insert into sales.city (name, state_id) values ('Banjar Dauhpangkung', 724);
insert into sales.city (name, state_id) values ('Tanahbeureum', 201);
insert into sales.city (name, state_id) values ('Limanowa', 691);
insert into sales.city (name, state_id) values ('Almodôvar', 338);
insert into sales.city (name, state_id) values ('Lucapa', 700);
insert into sales.city (name, state_id) values ('Saint-Louis', 966);
insert into sales.city (name, state_id) values ('Juegang', 712);
insert into sales.city (name, state_id) values ('Greenville', 502);
insert into sales.city (name, state_id) values ('Edsbyn', 86);
insert into sales.city (name, state_id) values ('Morohongō', 75);
insert into sales.city (name, state_id) values ('Tilburg', 174);
insert into sales.city (name, state_id) values ('Bojadła', 732);
insert into sales.city (name, state_id) values ('Lazaro Cardenas', 605);
insert into sales.city (name, state_id) values ('Xincun', 236);
insert into sales.city (name, state_id) values ('Rio Verde de Mato Grosso', 939);
insert into sales.city (name, state_id) values ('Reconquista', 30);
insert into sales.city (name, state_id) values ('Boden', 844);
insert into sales.city (name, state_id) values ('Tužno', 671);
insert into sales.city (name, state_id) values ('Solna', 608);
insert into sales.city (name, state_id) values ('Baishan', 968);
insert into sales.city (name, state_id) values ('Helsingborg', 588);
insert into sales.city (name, state_id) values ('Kuala Lumpur', 407);
insert into sales.city (name, state_id) values ('Bambang', 777);
insert into sales.city (name, state_id) values ('Perugia', 50);
insert into sales.city (name, state_id) values ('Jiang’an', 291);
insert into sales.city (name, state_id) values ('Morteros', 532);
insert into sales.city (name, state_id) values ('San Jose', 622);
insert into sales.city (name, state_id) values ('Palue', 756);
insert into sales.city (name, state_id) values ('Taiping', 260);
insert into sales.city (name, state_id) values ('Karangpeton', 110);
insert into sales.city (name, state_id) values ('Odiongan', 926);
insert into sales.city (name, state_id) values ('Armentières', 947);
insert into sales.city (name, state_id) values ('Heishui', 630);
insert into sales.city (name, state_id) values ('Na Klang', 274);
insert into sales.city (name, state_id) values ('Belmullet', 239);
insert into sales.city (name, state_id) values ('Ojo de Agua', 403);
insert into sales.city (name, state_id) values ('Corquín', 421);
insert into sales.city (name, state_id) values ('Saint-Égrève', 313);
insert into sales.city (name, state_id) values ('Cloyne', 763);
insert into sales.city (name, state_id) values ('Hotonj', 833);
insert into sales.city (name, state_id) values ('Nanxinxiang', 331);
insert into sales.city (name, state_id) values ('København', 816);
insert into sales.city (name, state_id) values ('Jiuxian', 7);
insert into sales.city (name, state_id) values ('Tiel', 540);
insert into sales.city (name, state_id) values ('Cabaret', 293);
insert into sales.city (name, state_id) values ('Xieqiao', 981);
insert into sales.city (name, state_id) values ('Zselickislak', 981);
insert into sales.city (name, state_id) values ('Charqueadas', 365);
insert into sales.city (name, state_id) values ('Ierápetra', 243);
insert into sales.city (name, state_id) values ('Gaphatshwe', 711);
insert into sales.city (name, state_id) values ('Changtang', 937);
insert into sales.city (name, state_id) values ('Horodnya', 500);
insert into sales.city (name, state_id) values ('Alkmaar', 818);
insert into sales.city (name, state_id) values ('Gustavsberg', 494);
insert into sales.city (name, state_id) values ('Nirgua', 942);
insert into sales.city (name, state_id) values ('Guandu', 210);
insert into sales.city (name, state_id) values ('Paris 16', 820);
insert into sales.city (name, state_id) values ('Borzoy', 252);
insert into sales.city (name, state_id) values ('Minna', 367);
insert into sales.city (name, state_id) values ('Colares', 342);
insert into sales.city (name, state_id) values ('Liuqu', 665);
insert into sales.city (name, state_id) values ('Izbicko', 951);
insert into sales.city (name, state_id) values ('Chaloem Phra Kiat', 4);
insert into sales.city (name, state_id) values ('Cishan', 40);
insert into sales.city (name, state_id) values ('Arwād', 260);
insert into sales.city (name, state_id) values ('Nanqiao', 569);
insert into sales.city (name, state_id) values ('Bershet’', 811);
insert into sales.city (name, state_id) values ('Göteborg', 147);
insert into sales.city (name, state_id) values ('Strasbourg', 863);
insert into sales.city (name, state_id) values ('Megion', 844);
insert into sales.city (name, state_id) values ('Airmata', 311);
insert into sales.city (name, state_id) values ('San Manuel', 639);
insert into sales.city (name, state_id) values ('Cube', 808);
insert into sales.city (name, state_id) values ('Capalonga', 334);
insert into sales.city (name, state_id) values ('Sumberejo', 8);
insert into sales.city (name, state_id) values ('Tuba', 396);
insert into sales.city (name, state_id) values ('Paris 09', 372);
insert into sales.city (name, state_id) values ('Ningzhong', 184);
insert into sales.city (name, state_id) values ('Afikpo', 806);
insert into sales.city (name, state_id) values ('Visby', 457);
insert into sales.city (name, state_id) values ('Tupsan', 515);
insert into sales.city (name, state_id) values ('Dengteke', 735);
insert into sales.city (name, state_id) values ('Odintsovo', 240);
insert into sales.city (name, state_id) values ('Puro Pinget', 300);
insert into sales.city (name, state_id) values ('Eslöv', 180);
insert into sales.city (name, state_id) values ('Campanário', 769);
insert into sales.city (name, state_id) values ('Cabimas', 689);
insert into sales.city (name, state_id) values ('Ankazondandy', 716);
insert into sales.city (name, state_id) values ('Nūbā', 512);
insert into sales.city (name, state_id) values ('Walichnowy', 499);
insert into sales.city (name, state_id) values ('El Caño', 879);
insert into sales.city (name, state_id) values ('Agen', 59);
insert into sales.city (name, state_id) values ('Timahankrajan', 781);
insert into sales.city (name, state_id) values ('Tancheng', 335);
insert into sales.city (name, state_id) values ('Aghada', 464);
insert into sales.city (name, state_id) values ('Salamá', 800);
insert into sales.city (name, state_id) values ('San Nicolas', 337);
insert into sales.city (name, state_id) values ('Vidnoye', 804);
insert into sales.city (name, state_id) values ('Ibadan', 781);
insert into sales.city (name, state_id) values ('Kansas City', 619);
insert into sales.city (name, state_id) values ('Dār Kulayb', 482);
insert into sales.city (name, state_id) values ('Speightstown', 209);
insert into sales.city (name, state_id) values ('Carpentras', 211);
insert into sales.city (name, state_id) values ('Zhoinda', 6);
insert into sales.city (name, state_id) values ('Engel’s', 326);
insert into sales.city (name, state_id) values ('Sakhipur', 422);
insert into sales.city (name, state_id) values ('Kristiansand S', 543);
insert into sales.city (name, state_id) values ('Ettal', 393);
insert into sales.city (name, state_id) values ('Pavlodar', 126);
insert into sales.city (name, state_id) values ('Brandýs nad Labem-Stará Boleslav', 891);
insert into sales.city (name, state_id) values ('Shuvakish', 753);
insert into sales.city (name, state_id) values ('Watangan', 384);
insert into sales.city (name, state_id) values ('Kradinan', 139);
insert into sales.city (name, state_id) values ('Calibishie', 391);
insert into sales.city (name, state_id) values ('Maripipi', 871);
insert into sales.city (name, state_id) values ('Masuda', 245);
insert into sales.city (name, state_id) values ('Balitoc', 241);
insert into sales.city (name, state_id) values ('Narawayong', 54);
insert into sales.city (name, state_id) values ('Buchach', 690);
insert into sales.city (name, state_id) values ('Abaeté', 760);
insert into sales.city (name, state_id) values ('Luleå', 517);
insert into sales.city (name, state_id) values ('Lizhai', 987);
insert into sales.city (name, state_id) values ('São Tomé', 709);
insert into sales.city (name, state_id) values ('Luobuqiongzi', 558);
insert into sales.city (name, state_id) values ('Manzanillo', 213);
insert into sales.city (name, state_id) values ('Pudoc', 527);
insert into sales.city (name, state_id) values ('Changpu', 826);
insert into sales.city (name, state_id) values ('Kropachëvo', 499);
insert into sales.city (name, state_id) values ('Beaumont', 800);
insert into sales.city (name, state_id) values ('Oskarshamn', 814);
insert into sales.city (name, state_id) values ('Parchal', 124);
insert into sales.city (name, state_id) values ('La Guata', 455);
insert into sales.city (name, state_id) values ('Manukau City', 622);
insert into sales.city (name, state_id) values ('Shuangfeng', 637);
insert into sales.city (name, state_id) values ('Brive-la-Gaillarde', 271);
insert into sales.city (name, state_id) values ('Dali', 603);
insert into sales.city (name, state_id) values ('Caridade', 820);
insert into sales.city (name, state_id) values ('Bearna', 903);
insert into sales.city (name, state_id) values ('Mogzon', 119);
insert into sales.city (name, state_id) values ('Gornyy', 998);
insert into sales.city (name, state_id) values ('Ćmielów', 166);
insert into sales.city (name, state_id) values ('Salaya', 196);
insert into sales.city (name, state_id) values ('Hīsh', 454);
insert into sales.city (name, state_id) values ('Monkey Hill', 854);
insert into sales.city (name, state_id) values ('Dami', 330);
insert into sales.city (name, state_id) values ('Anastácio', 400);
insert into sales.city (name, state_id) values ('Vermoim', 543);
insert into sales.city (name, state_id) values ('San Bernardino', 797);
insert into sales.city (name, state_id) values ('Nakama', 481);
insert into sales.city (name, state_id) values ('Kotingnatagete', 819);
insert into sales.city (name, state_id) values ('Qarqania', 752);
insert into sales.city (name, state_id) values ('Gizo', 813);
insert into sales.city (name, state_id) values ('Morales', 662);
insert into sales.city (name, state_id) values ('Gołkowice', 166);
insert into sales.city (name, state_id) values ('Qiaojia', 782);
insert into sales.city (name, state_id) values ('Sikka', 642);
insert into sales.city (name, state_id) values ('Três Rios', 394);
insert into sales.city (name, state_id) values ('Lijie', 161);
insert into sales.city (name, state_id) values ('Viengxay', 259);
insert into sales.city (name, state_id) values ('La Joya', 19);
insert into sales.city (name, state_id) values ('Wilków', 225);
insert into sales.city (name, state_id) values ('Asheville', 478);
insert into sales.city (name, state_id) values ('Kozhva', 319);
insert into sales.city (name, state_id) values ('Khotiv', 576);
insert into sales.city (name, state_id) values ('Montecristi', 637);
insert into sales.city (name, state_id) values ('Yaruchel', 254);
insert into sales.city (name, state_id) values ('Yuanshanzi', 322);
insert into sales.city (name, state_id) values ('Kwolla', 91);
insert into sales.city (name, state_id) values ('Uusikaupunki', 582);
insert into sales.city (name, state_id) values ('Joaquín Suárez', 465);
insert into sales.city (name, state_id) values ('Aiánteio', 837);
insert into sales.city (name, state_id) values ('Wangsi', 602);
insert into sales.city (name, state_id) values ('Bama', 228);
insert into sales.city (name, state_id) values ('Temirtau', 268);
insert into sales.city (name, state_id) values ('Chinchaypujio', 655);
insert into sales.city (name, state_id) values ('Wangji', 672);
insert into sales.city (name, state_id) values ('‘Afak', 688);
insert into sales.city (name, state_id) values ('Piskivka', 231);
insert into sales.city (name, state_id) values ('Mayenne', 655);
insert into sales.city (name, state_id) values ('Yuqian', 544);
insert into sales.city (name, state_id) values ('Rogóźno', 390);
insert into sales.city (name, state_id) values ('Debesy', 587);
insert into sales.city (name, state_id) values ('Papelón', 907);
insert into sales.city (name, state_id) values ('城郊', 65);
insert into sales.city (name, state_id) values ('Dundrum', 133);
insert into sales.city (name, state_id) values ('Seversk', 887);
insert into sales.city (name, state_id) values ('Maketu', 247);
insert into sales.city (name, state_id) values ('Coromandel', 874);
insert into sales.city (name, state_id) values ('Vale de Rolas', 816);
insert into sales.city (name, state_id) values ('Dresden', 290);
insert into sales.city (name, state_id) values ('Visoko', 368);
insert into sales.city (name, state_id) values ('Nāḩiyat as Sab‘ Biyār', 585);
insert into sales.city (name, state_id) values ('Popova', 721);
insert into sales.city (name, state_id) values ('Pingle', 853);
insert into sales.city (name, state_id) values ('Le Havre', 161);
insert into sales.city (name, state_id) values ('Sunzhuang', 639);
insert into sales.city (name, state_id) values ('Hengshitang', 257);
