insert into sales.products (name, cat_id, color, description, price) values ('Diapers', 1, 'White', 'Best for baby bums', 12.50);
insert into sales.products (name, cat_id, color, description, price) values ('Wipes', 1, 'White', 'Organic solution to toxic problems', 8);
insert into sales.products (name, cat_id, color, description, price) values ('Rattle', 1, 'Yellow', 'Soothing Toy', 4);
insert into sales.products (name, cat_id, color, description, price) values ('Puzzle', 2, NULL, NULL, 12.25);
insert into sales.products (name, cat_id, color, description, price) values ('Vida', 2, NULL, 'A game about the ups and downs of life.', 10);
insert into sales.products (name, cat_id, color, description, price) values ('No Clue', 2, NULL, 'Detectie mystery', 10);
insert into sales.products (name, cat_id, color, description, price) values ('Wipers', 3, 'Black', 'Windshield Wipers', 14.99);
insert into sales.products (name, cat_id, color, description, price) values ('Air Freshener', 3, NULL, 'Strawberry Scent', 4.99);
insert into sales.products (name, cat_id, color, description, price) values ('Floor Mats', 3, 'Black', 'Four rubber mats', 40);
insert into sales.products (name, cat_id, color, description, price) values ('Never Stop Learning', 4, NULL, 'An inspirational tale of lifelong learning.', 10.99);
insert into sales.products (name, cat_id, color, description, price) values ('Learn By Doing', 4, NULL, 'Real life examples for getting real world experience.', 12);
insert into sales.products (name, cat_id, color, description, price) values ('Be Awesome', 4, NULL, 'Why would you not want to be awesome?', 15);
insert into sales.products (name, cat_id, color, description, price) values ('Ultra Awesome Machine', 5, 'Red', 'The fastest desktop on the market', 1000);
insert into sales.products (name, cat_id, color, description, price) values ('Thinpad 3000', 5, 'Silver', 'A laptop so thin that you wonder what you are paying for.', 2000);
insert into sales.products (name, cat_id, color, description, price) values ('Ultra-wide Megascreen', 5, 'Black', 'High resolution gaming monitor.', 600);
insert into sales.products (name, cat_id, color, description, price) values ('Comfy N1', 6, 'Blue', 'Comfortable walking shoes', 40);
insert into sales.products (name, cat_id, color, description, price) values ('FastGuy', 6, 'Red', 'You know they make you fast because they are red.', 50);
insert into sales.products (name, cat_id, color, description, price) values ('Surfside Stroller', 6, 'Grey', 'Sandals for taking in the aquatic view', 25);
insert into sales.products (name, cat_id, color, description, price) values ('Hammer', 7, 'Brown', 'Light duty hammer', 15);
insert into sales.products (name, cat_id, color, description, price) values ('Screwdriver', 7, 'Silver', 'Universal screwdriver', 12);
insert into sales.products (name, cat_id, color, description, price) values ('Wrench', 7, 'Silver', 'Universal wrench', 12);
insert into sales.products (name, cat_id, color, description, price) values ('Flower Seed', 8, NULL, 'Mystery pack', 5);
insert into sales.products (name, cat_id, color, description, price) values ('Rake', 8, 'Black', 'Garden rake', 10);
insert into sales.products (name, cat_id, color, description, price) values ('Mulch', 8, 'Brown', '50 pound bag', 30);
insert into sales.products (name, cat_id, color, description, price) values ('Basketball', 9, 'Orange', 'Standard size basketball', 15);
insert into sales.products (name, cat_id, color, description, price) values ('Football', 9, 'Brown', 'Standard size football', 15);
insert into sales.products (name, cat_id, color, description, price) values ('Tent', 9, 'Green', 'Four person tent', 50);
insert into sales.products (name, cat_id, color, description, price) values ('Lipstick', 10, 'Pink', NULL, 20);
insert into sales.products (name, cat_id, color, description, price) values ('Brush', 10, 'Purple', 'Hair brush', 4.99);
insert into sales.products (name, cat_id, color, description, price) values ('Hand Cream', 10, 'White', 'Moisterizing lotion', 20);
insert into sales.products (name, cat_id, color, description, price) values ('Pythons on a Plane', 11, NULL, 'A thrilling adventure of how our own systems trap us.', 15);
insert into sales.products (name, cat_id, color, description, price) values ('A Tale of Two Clouds', 11, NULL, 'Their love of automation will transcend cloud borders and unite warring dev groups.', 15);
insert into sales.products (name, cat_id, color, description, price) values ('Shell Shock', 11, NULL, 'By day he is a lowly sys admin, by night he becomes the fearsome SHELL SHOCK.', 15);
insert into sales.products (name, cat_id, color, description, price) values ('MyPad', 12, 'Silver', 'It''s the best, because it''s made by them.', 500);
insert into sales.products (name, cat_id, color, description, price) values ('ViewThings X11', 12, 'Black', '50'' TV', 200);
insert into sales.products (name, cat_id, color, description, price) values ('Bingetendo Twitch', 12, 'Yellow', 'Cutting edge enough that we can charge full price.', 300);